/*
 * Overseerr API
 *
 * This is the documentation for the Overseerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Overseerr. 
 *
 * The version of the OpenAPI document: v1.33.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MainSettings {
    #[serde(rename = "apiKey", skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(rename = "appLanguage", skip_serializing_if = "Option::is_none")]
    pub app_language: Option<String>,
    #[serde(rename = "applicationTitle", skip_serializing_if = "Option::is_none")]
    pub application_title: Option<String>,
    #[serde(rename = "applicationUrl", skip_serializing_if = "Option::is_none")]
    pub application_url: Option<String>,
    #[serde(rename = "trustProxy", skip_serializing_if = "Option::is_none")]
    pub trust_proxy: Option<bool>,
    #[serde(rename = "csrfProtection", skip_serializing_if = "Option::is_none")]
    pub csrf_protection: Option<bool>,
    #[serde(rename = "hideAvailable", skip_serializing_if = "Option::is_none")]
    pub hide_available: Option<bool>,
    #[serde(rename = "partialRequestsEnabled", skip_serializing_if = "Option::is_none")]
    pub partial_requests_enabled: Option<bool>,
    #[serde(rename = "localLogin", skip_serializing_if = "Option::is_none")]
    pub local_login: Option<bool>,
    #[serde(rename = "newPlexLogin", skip_serializing_if = "Option::is_none")]
    pub new_plex_login: Option<bool>,
    #[serde(rename = "defaultPermissions", skip_serializing_if = "Option::is_none")]
    pub default_permissions: Option<f64>,
}

impl MainSettings {
    pub fn new() -> MainSettings {
        MainSettings {
            api_key: None,
            app_language: None,
            application_title: None,
            application_url: None,
            trust_proxy: None,
            csrf_protection: None,
            hide_available: None,
            partial_requests_enabled: None,
            local_login: None,
            new_plex_login: None,
            default_permissions: None,
        }
    }
}

